kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "cert-manager-csi-driver-athenz.labels" . | indent 4 }}
  name: {{ include "cert-manager-csi-driver-athenz.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cert-manager-csi-driver-athenz.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "cert-manager-csi-driver-athenz.name" . }}
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "cert-manager-csi-driver-athenz.labels" . | indent 4 }}
  name: {{ include "cert-manager-csi-driver-athenz.name" . }}-approver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cert-manager-csi-driver-athenz.name" . }}-approver
subjects:
- kind: ServiceAccount
  name: {{ include "cert-manager-csi-driver-athenz.name" . }}-approver
  namespace: {{ .Release.Namespace }}
