{{- if and .Values.app.approver.metrics.service.enabled .Values.app.approver.metrics.service.servicemonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "csi-driver-athenz.name" . }}-approver
  labels:
    app: {{ include "csi-driver-athenz.name" . }}-approver
{{ include "csi-driver-athenz.labels" . | indent 4 }}
    prometheus: {{ .Values.app.approver.metrics.service.servicemonitor.prometheusInstance }}
{{- if .Values.app.approver.metrics.service.servicemonitor.labels }}
{{ toYaml .Values.app.approver.metrics.service.servicemonitor.labels | indent 4}}
{{- end }}
spec:
  jobLabel: {{ include "csi-driver-athenz.name" . }}-approver
  selector:
    matchLabels:
      app: {{ include "csi-driver-athenz.name" . }}-approver
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - targetPort: {{ .Values.app.approver.metrics.port }}
    path: "/metrics"
    interval: {{ .Values.app.approver.metrics.service.servicemonitor.interval }}
    scrapeTimeout: {{ .Values.app.approver.metrics.service.servicemonitor.scrapeTimeout }}
{{- end }}
