{{- if .Values.app.approver.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "csi-driver-athenz.name" . }}-approver-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "csi-driver-athenz.name" . }}-approver
{{ include "csi-driver-athenz.labels" . | indent 4 }}
spec:
  type: {{ .Values.app.approver.metrics.service.type }}
  ports:
    - port: {{ .Values.app.approver.metrics.port }}
      targetPort: {{ .Values.app.approver.metrics.port }}
      protocol: TCP
      name: metrics
  selector:
    app: {{ include "csi-driver-athenz.name" . }}-approver
{{- end }}
