kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "csi-driver-athenz.name" . }}-approver
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "csi-driver-athenz.labels" . | indent 4 }}
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "update", "create"]
