apiVersion: v1
kind: ServiceAccount
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
    {{- toYaml . | nindent 8 }}
{{- end }}
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "cert-manager-csi-driver-athenz.labels" . | indent 4 }}
  name: {{ include "cert-manager-csi-driver-athenz.name" . }}
---
apiVersion: v1
kind: ServiceAccount
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
    {{- toYaml . | nindent 8 }}
{{- end }}
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "cert-manager-csi-driver-athenz.labels" . | indent 4 }}
  name: {{ include "cert-manager-csi-driver-athenz.name" . }}-approver
